name: Docker Image CI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions: 
  packages: write
  
env:
  APP_NAME: rdtclient
  DOCKER_FILE: ./Dockerfile
  DOCKER_PLATFORMS: "linux/arm64/v8,linux/amd64"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ github.repository_owner }}/${{ env.APP_NAME }}
        tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.5.0
      with:
        buildkitd-flags: --debug

    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    #- name: Login to GHCR
    #  if: ${{ github.event_name != 'pull_request' }}
    #  uses: docker/login-action@v2.1.0
    #  with:
    #    registry: ghcr.io
    #    username: ${{ github.repository_owner }}
    #    password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ${{ env.DOCKER_FILE }}
        platforms: ${{ env.DOCKER_PLATFORMS }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
